
**Pandas DataFrame Detective**

In [6]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve', 'Frank'],
    'Age': [25, 30, np.nan, 35, 28, np.nan],
    'Score': [85, 92, 78, np.nan, 88, 95],
    'Grade': ['A', 'A', 'B', 'C', 'B', 'A']
}

df = pd.DataFrame(data)
df

      Name   Age  Score Grade
0    Alice  25.0   85.0     A
1      Bob  30.0   92.0     A
2  Charlie   NaN   78.0     B
3    Diana  35.0    NaN     C
4      Eve  28.0   88.0     B
5    Frank   NaN   95.0     A

In [7]:
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Age']

0    25.0
1    30.0
2    29.5
3    35.0
4    28.0
5    29.5
Name: Age, dtype: float64

In [8]:
df = df.dropna(subset=['Score'])
df

      Name   Age  Score Grade
0    Alice  25.0   85.0     A
1      Bob  30.0   92.0     A
2  Charlie  29.5   78.0     B
4      Eve  28.0   88.0     B
5    Frank  29.5   95.0     A

In [9]:
df.set_index('Name', inplace=True)